name: shopizy
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: null
  badges: ^2.0.1
  cached_network_image: ^3.0.0-nullsafety
  carousel_slider: ^4.0.0-nullsafety.0
  confirm_dialog: ^1.0.0
  crypto: ^3.0.1
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_messaging: ^11.1.0
  flutter:
    sdk: flutter
  flutter_html: ^2.0.0
  flutter_i18n: ^0.22.3
  flutter_local_notifications: ^5.0.0+4
  flutter_localizations:
    sdk: flutter
  flutter_number_picker: ^1.0.4
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^7.1.8
  get: ^4.0.0-nullsafety.2
  get_storage: ^2.0.1
  http: ^0.13.1
  intl: ^0.17.0
  launch_review: ^1.0.1
  libphonenumber: ^1.0.2
  percent_indicator: ^3.0.1
  pin_code_fields: ^7.2.0
  provider:
  rate_my_app: ^1.1.0+1
  share: ^2.0.4
  shimmer: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.10
  webview_flutter: ^2.0.8
  flutter_math_fork: ^0.4.0
  flutter_svg : ^0.22.0
  firebase_analytics: ^9.0.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Regular.otf
        - asset: assets/fonts/Helvetica-Medium.otf
          weight: 500
        - asset: assets/fonts/Helvetica-Bold.otf
          weight: 700
        - asset: assets/fonts/Helvetica-ExtraBold.otf
          weight: 900
